### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath#71]
While not mentioned in the spec, JSON Schema is often represented in YAML rather than JSON for various reasons.  OpenAPI is a common example of this.

(Personally I don't like YAML, but my opinions seem to have no effect on it's continued public use.)

Is processing a JSON Path over YAML data something that we want to consider for the specification, or do we leave that to the implementations to decide (as JSON Schema does)?

**Comment by cabo** [comment]
It could be mentioned, but will otherwise have no influence on the specification, so I dont's see a reason for that.

**Comment by glyn** [comment]
I wrote https://github.com/vmware-labs/yaml-jsonpath/ because of a need to
apply JSONPath to YAML data (Kubernetes resource files). But I would prefer
to avoid importing the additonal complexity of YAML into our internet draft
as I don't think it adds sufficient value and I doubt many JSONPath
implementations would support YAML.

**Comment by cabo** [comment]
One can always write a spec that explains how to apply JSONPath to more extensive data models than that of JSON (and probably extend it in the process).  But that is not what this WG is chartered to do.

**Comment by gregsdennis** [comment]
I think we have a consensus to not support YAML at this time.  Closing the issue.
